/*
 * This source file was generated by the Gradle 'init' task
 */
package expression.builder;

import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.UIManager;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Application.launch(ExpressionNodeExplorer.class, args);
        // 1. Set the System Look and Feel (optional, but recommended)
        /*try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            // Fallback to default Metal look and feel
            System.err.println("Could not load system Look and Feel: " + e.getMessage());
        }

        // 2. Schedule the GUI creation on the Event Dispatch Thread
        EventQueue.invokeLater(() -> {
            try {
                createAndShowGUI();
            } catch (Exception e) {
                e.printStackTrace();
            }
        });*/
    }

    private static void createAndShowGUI() {
        // 3. Create the main application window (Frame)
        JFrame frame = new JFrame("HEC Expression Builder - Wizard");
        
        // Exit the application when the window is closed
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // 4. Instantiate your wizard panel
        ExpressionWizardPanel wizardPanel = new ExpressionWizardPanel();

        // 5. Add the panel to the frame's content pane
        // The panel uses BorderLayout, so it will fill the frame
        frame.add(wizardPanel);

        // 6. Set the window size and make it visible
        // 950x650 provides enough space for the template panel and all form fields
        frame.setSize(950, 650);
        
        // Center the window on the user's screen
        frame.setLocationRelativeTo(null);
        
        // Show the window
        frame.setVisible(true);
    }
}
